Suggestion for reviewers
tobyhodges/lesson-sprint-recommendations pull request #19
Opened 2020-12-30 18:29 UTC by sstevens2

2021-01-04 09:52 UTC, tobyhodges requested changes
These are fantastic recommendations, @sstevens2. I've suggested a few small typo fixes and one other adjustment.

2021-01-04 09:52 UTC, tobyhodges commented on during.md
> +  Make a plan for who will review each Rull Request.
```suggestion
  Make a plan for who will review each Pull Request.
```

2021-01-04 09:52 UTC, tobyhodges commented on during.md
> +  As a group you can create list of reviewers by subject so the person who opens the Pull Reqest knows who to is interested and capable of reviewing.
```suggestion
  As a group you can create list of reviewers by subject so the person who opens the Pull Request knows who is interested and capable of reviewing and can request a review accordingly.
```

2021-01-04 09:52 UTC, tobyhodges commented on during.md
> +  Alternatively, maybe you decide on circle of reviewers. E.g. Aaliyah reviews Juan's PRs, Juan reivews Alex's PRs, and Alex reviews Aaliyah's PRs.
```suggestion
  Alternatively, you may decide on a circle of reviewers. E.g. Aaliyah reviews Juan's PRs, Juan reviews Alex's PRs, and Alex reviews Aaliyah's PRs.
```

2021-01-06 20:48 UTC, sstevens2 commented
Thanks for the review and feedback!

2021-01-07 08:32 UTC, tobyhodges approved these changes

2021-01-07 08:32 UTC, merged